In [ ]:
1. Create a null vector of size 10 but the fifth value which is 1.
2. Create a vector with values ranging from 10 to 49.
3. Create a 3x3 matrix with values ranging from 0 to 8
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 10x10 array with random values and find the minimum and maximum values.
6. Create a random vector of size 30 and find the mean value.


In [10]:
# 1.  Create a null vector  of  size 10 but the fifth value which is 1.
import numpy as np  
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
# 2. Create a vector with values ranging from 10 to 49.
import numpy as np
array  = np.arange(10,49)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [13]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
import  numpy as  np  
matrix =  np.random.randint(low = 0 , high = 8, size = (3,3))
matrix


array([[5, 6, 2],
       [4, 1, 0],
       [2, 0, 3]])

In [14]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0] 
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

In [19]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
import  numpy as  np  
matrix =  np.random.randint(0,100,(10,10))
print('Minimum values :',matrix.min())
print('Maximum values :',matrix.max())


Minimum values : 0
Maximum values : 99


In [22]:
# 6. Create a random vector of size 30 and find the mean value.
arr = np.random.random(30)
print(arr)
arr.mean()

[0.52632141 0.0653495  0.42023352 0.58764364 0.01169405 0.0993147
 0.95457147 0.39071389 0.63190365 0.24224357 0.67779033 0.09656895
 0.19904095 0.99382439 0.71266762 0.62407329 0.58266573 0.95412269
 0.21990785 0.10882869 0.70059972 0.32561007 0.33275229 0.16051302
 0.03881248 0.55895972 0.70348313 0.86977558 0.513183   0.8444501 ]


0.47158729955476625